<?php


/**
 * This class defines the structure of the 'customers' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 21 03:15:55 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CustomersTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CustomersTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('customers');
		$this->setPhpName('Customers');
		$this->setClassname('Customers');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('CUSTOMER_ID', 'CustomerId', 'INTEGER', true, null, null);
		$this->addColumn('CUSTOMER_NAME', 'CustomerName', 'VARCHAR', false, 100, null);
		$this->addColumn('CUSTOMER_ADRESS', 'CustomerAdress', 'VARCHAR', false, 255, null);
		$this->addColumn('CUSTOMER_ZIP_CODE', 'CustomerZipCode', 'VARCHAR', false, 6, null);
		$this->addColumn('CUSTOMER_CITY', 'CustomerCity', 'VARCHAR', false, 255, null);
		$this->addColumn('CUSTOMER_NIP', 'CustomerNip', 'VARCHAR', false, 15, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Invoices', 'Invoices', RelationMap::ONE_TO_MANY, array('customer_id' => 'customer_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CustomersTableMap
