<?php


/**
 * This class defines the structure of the 'invoices' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 21 03:15:55 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class InvoicesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.InvoicesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('invoices');
		$this->setPhpName('Invoices');
		$this->setClassname('Invoices');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('INVOICE_ID', 'InvoiceId', 'INTEGER', true, null, null);
		$this->addForeignKey('COMPANY_ID', 'CompanyId', 'INTEGER', 'companies', 'COMPANY_ID', true, null, null);
		$this->addColumn('ISSUED_DATE', 'IssuedDate', 'DATE', false, null, null);
		$this->addColumn('SERVICE_NAME', 'ServiceName', 'VARCHAR', false, 255, null);
		$this->addColumn('SOLD_DATE', 'SoldDate', 'DATE', false, null, null);
		$this->addForeignKey('CUSTOMER_ID', 'CustomerId', 'INTEGER', 'customers', 'CUSTOMER_ID', true, null, null);
		$this->addColumn('PRICE_NETTO', 'PriceNetto', 'DECIMAL', false, 11, null);
		$this->addColumn('PRICE_BRUTTO', 'PriceBrutto', 'DECIMAL', false, 11, null);
		$this->addColumn('VALUE_TAX', 'ValueTax', 'DECIMAL', false, 11, null);
		$this->addColumn('TAX', 'Tax', 'DECIMAL', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Companies', 'Companies', RelationMap::MANY_TO_ONE, array('company_id' => 'company_id', ), null, null);
    $this->addRelation('Customers', 'Customers', RelationMap::MANY_TO_ONE, array('customer_id' => 'customer_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // InvoicesTableMap
