<?php


/**
 * Skeleton subclass for performing query and update operations on the 'companies' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 21 00:35:59 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CompaniesPeer extends BaseCompaniesPeer {

} // CompaniesPeer
