<?php


/**
 * Skeleton subclass for performing query and update operations on the 'invoices' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 21 03:13:19 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class InvoicesPeer extends BaseInvoicesPeer {

} // InvoicesPeer
